# Generated by Django 6.0.3 on 2026-06-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklylogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('returned', 'Returned')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='supervisor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
