# Generated by Django 6.0.3 on 2026-04-17 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.placement'),
        ),
    ]
