# Generated by Django 6.0.6 on 2026-07-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('work_supervisor', 'Workplace Supervisor'), ('academic_supervisor', 'Academic Supervisor'), ('admin', 'Admin')], max_length=20),
        ),
    ]
